# stage1_metadata.py
# Stage 1: Metadata and EXIF inspection. Free, local, no HTTP requests.
#
# Detection layers (in order of reliability):
#   1. Software / Creator EXIF tag  ← AI tools (Midjourney, DALL-E, Firefly, SD) self-identify here
#   2. PNG text chunks              ← Stable Diffusion / ComfyUI embed full prompt + params
#   3. XMP / IPTC AI claims         ← Adobe Firefly, DALL-E content credentials
#   4. C2PA manifest bytes          ← OpenAI DALL-E, Adobe, newer tools
#   5. Camera EXIF richness         ← Real cameras leave abundant metadata; AI tools rarely do
#   6. Suspicious field patterns    ← Known AI-only field combinations or missing critical fields

import json
import os
import re
import struct
from datetime import datetime, timezone
from PIL import Image, ExifTags




# ── Known AI generator fingerprints ──────────────────────────────────────────

# Software tags that are definitive proof of AI generation
_AI_SOFTWARE_EXACT = {
    "midjourney",
    "dall-e",
    "dall·e",
    "stable diffusion",
    "adobe firefly",
    "dreamstudio",
    "imagen",
    "stable-diffusion",
    "comfyui",
    "invokeai",
    "automatic1111",
    "sdxl",
    "novelai",
    "playground ai",
    "nightcafe",
    "leonardo.ai",
    "ideogram",
    "blue willow",
    "getimg.ai",
    "seaart",
    "tensor.art",
}

# Partial substrings that, if found in a software/creator field, strongly suggest AI
_AI_SOFTWARE_PARTIAL = [
    "midjourney",
    "stable diffusion",
    "dall-e",
    "dall·e",
    "firefly",
    "dreamstudio",
    "comfyui",
    "invokeai",
    "novelai",
    "imagine.art",
    "bing image creator",
    "adobe generative",
    "ai-generated",
    "generated by ai",
    "generative fill",
    "dreamboothv",
    "lora",         # careful – only in software field context
    "controlnet",
    "nai diffusion",
    "flux.1",
    "flux-dev",
    "flux-schnell",
]

# PNG tEXt chunk keys used by AI generators
_SD_PNG_KEYS = {
    "parameters",       # A1111 / WebUI
    "prompt",           # ComfyUI / InvokeAI
    "workflow",         # ComfyUI node graph
    "negative_prompt",
    "comment",          # some forks
    "sd metadata",
    "dreamstudio",
    "invokeai_metadata",
    "invokeai_graph",
    "naidata",          # NovelAI
    "description",      # MJ sometimes uses this
}

# Tokens inside PNG text / XMP that strongly indicate AI generation
_AI_CONTENT_TOKENS = [
    "steps:", "sampler:", "cfg scale:", "seed:", "model hash:",
    "negative prompt:", "denoising strength:", "clip skip:",
    "hires upscale:", "hires steps:", "hires upscaler:",
    "midjourney", "stable diffusion", "dall-e", "dall·e",
    "adobe firefly", "dreamstudio", "comfyui", "novelai",
    "generative ai", "ai-generated", "text-to-image",
    "ai generated", "generated image", "bing image creator",
    "flux.1", "flux-dev", "flux-schnell",
    "stablediffusion", "latent diffusion",
]

# XMP namespaces / properties associated with AI provenance
_XMP_AI_TOKENS = [
    "iptc4xmpext:digitalsourcetype",
    "trainedAlgorithmicMedia",
    "compositeSynthetic",
    "compositeWithTrainedAlgorithmicMedia",
    "ai.generated",
    "c2pa:assertion",
    "aiserv:",
    "generativeai:",
    "adobe:firefly",
    "Iptc4xmpExt:DigitalSourceType",
]

# Real camera manufacturers (lower-case)
_REAL_CAMERA_MAKES = {
    "canon", "nikon", "sony", "fujifilm", "olympus", "panasonic",
    "leica", "hasselblad", "phase one", "pentax", "ricoh", "sigma",
    "samsung", "apple", "google", "huawei", "xiaomi", "oneplus",
    "motorola", "lg", "htc", "nokia",
}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _ts() -> str:
    return datetime.now().strftime("[%H:%M:%S]")


def _empty_result(image_path: str, error: str) -> dict:
    return {
        "stage": 1,
        "image_path": image_path,
        # Definitive signals
        "ai_software_detected": False,
        "ai_software_name": None,
        "sd_png_params_found": False,
        "xmp_ai_claim_found": False,
        "has_c2pa": False,
        "c2pa_verdict": "unknown",
        # EXIF richness
        "has_exif": False,
        "exif_score": 0.5,
        "camera_make": None,
        "camera_model": None,
        "datetime_original": None,
        "has_gps": False,
        "real_camera_make": False,
        # File props
        "file_size_kb": 0,
        "format": "unknown",
        "width": 0,
        "height": 0,
        # Stage 1 verdict
        "stage1_ai_score": 0.5,
        "stage1_signals": [],
        "early_exit": False,
        "early_exit_verdict": None,
        "pipeline_notes": [],
        "error": error,
    }


def _lower_str(val) -> str:
    """Safely convert any value to lower-case string."""
    try:
        return str(val).lower()
    except Exception:
        return ""


def _contains_ai_token(text: str, tokens: list) -> tuple[bool, str]:
    """Check if text contains any AI token. Returns (found, matched_token)."""
    t = text.lower()
    for token in tokens:
        if token.lower() in t:
            return True, token
    return False, ""


# ── PNG chunk reader ──────────────────────────────────────────────────────────

def _read_png_text_chunks(image_path: str) -> dict[str, str]:
    """
    Read PNG tEXt and iTXt chunks directly from the file binary.
    Returns dict of {keyword: text_value}.
    Pillow's img.info may not expose all chunks reliably across versions.
    """
    chunks = {}
    try:
        with open(image_path, "rb") as fh:
            signature = fh.read(8)
            if signature != b"\x89PNG\r\n\x1a\n":
                return chunks  # Not a PNG

            while True:
                header = fh.read(8)
                if len(header) < 8:
                    break
                length = struct.unpack(">I", header[:4])[0]
                chunk_type = header[4:8].decode("ascii", errors="replace")
                data = fh.read(length)
                fh.read(4)  # CRC

                if chunk_type == "tEXt":
                    # keyword\x00text
                    null_idx = data.find(b"\x00")
                    if null_idx != -1:
                        key = data[:null_idx].decode("latin-1", errors="replace").strip()
                        val = data[null_idx + 1:].decode("latin-1", errors="replace")
                        chunks[key] = val

                elif chunk_type == "iTXt":
                    # keyword\x00compression_flag\x00compression_method\x00lang\x00translated_keyword\x00text
                    null_idx = data.find(b"\x00")
                    if null_idx != -1:
                        key = data[:null_idx].decode("latin-1", errors="replace").strip()
                        rest = data[null_idx + 1:]
                        # Skip compression_flag (1 byte), method (1 byte), then null-terminated lang, null-terminated xlated key
                        if len(rest) >= 2:
                            rest = rest[2:]
                            # skip language tag
                            n1 = rest.find(b"\x00")
                            if n1 != -1:
                                rest = rest[n1 + 1:]
                                # skip translated keyword
                                n2 = rest.find(b"\x00")
                                if n2 != -1:
                                    val = rest[n2 + 1:].decode("utf-8", errors="replace")
                                    chunks[key] = val

                elif chunk_type == "IEND":
                    break
    except Exception:
        pass
    return chunks


# ── XMP reader ────────────────────────────────────────────────────────────────

def _extract_xmp(image_path: str, img_info: dict) -> str:
    """Extract raw XMP string from PIL info dict or raw file bytes."""
    # Pillow may store XMP under various keys
    for key in ("xmp", "XML:com.adobe.xmp", "xml:com.adobe.xmp"):
        val = img_info.get(key)
        if val:
            if isinstance(val, bytes):
                return val.decode("utf-8", errors="replace")
            return str(val)

    # Fallback: scan first 128KB of the file for XMP packet
    try:
        with open(image_path, "rb") as fh:
            raw = fh.read(131072)
        start = raw.find(b"<?xpacket begin")
        if start == -1:
            start = raw.find(b"<x:xmpmeta")
        if start != -1:
            end = raw.find(b"</x:xmpmeta>", start)
            if end != -1:
                return raw[start: end + 12].decode("utf-8", errors="replace")
    except Exception:
        pass
    return ""


# ── C2PA / JUMBF byte scan ────────────────────────────────────────────────────

def _scan_c2pa(image_path: str) -> tuple[bool, str]:
    """
    Scan image bytes for C2PA / JUMBF / content-credentials markers.
    Returns (found, source_description).
    """
    try:
        with open(image_path, "rb") as fh:
            # C2PA manifests can appear anywhere; scan full file up to 2MB
            raw = fh.read(2097152)
    except Exception:
        return False, ""

    markers = [
        (b"c2pa", "c2pa marker"),
        (b"jumbf", "JUMBF box"),
        (b"contentauthenticity", "Content Authenticity"),
        (b"content_credentials", "Content Credentials"),
        (b"content credentials", "Content Credentials"),
        (b"c2pa.assertions", "c2pa.assertions"),
        (b"application/c2pa", "application/c2pa MIME"),
        (b"\x00\x00\x00\x0cjumb", "JUMBF box header"),
    ]

    raw_lower = raw.lower()
    for marker, label in markers:
        if marker in raw_lower:
            return True, label

    return False, ""


# ── Main run function ─────────────────────────────────────────────────────────

def run(image_path: str) -> dict:
    notes = []
    signals = []       # list of (signal_name, weight, direction) — direction: "ai" or "real"
    ai_score = 0.5     # will be computed from signals

    # ─────────────────────────────────────────────────────────────────────────
    # Step 1 — File validation
    # ─────────────────────────────────────────────────────────────────────────
    try:
        img = Image.open(image_path)
        img.verify()
        img = Image.open(image_path)  # re-open after verify()
    except Exception as exc:
        return _empty_result(image_path, f"invalid_file: {exc}")

    notes.append(f"{_ts()} File validation: image opened successfully")
    fmt = img.format or "unknown"
    width, height = img.size
    mode = img.mode or "unknown"
    img_info = img.info or {}

    try:
        file_size_kb = int(os.path.getsize(image_path) / 1024)
    except Exception:
        file_size_kb = 0

    notes.append(f"{_ts()} File properties: {fmt} {width}x{height} {mode} {file_size_kb}KB")

    # ─────────────────────────────────────────────────────────────────────────
    # Step 2 — EXIF extraction (all tags)
    # ─────────────────────────────────────────────────────────────────────────
    exif_data = {}
    camera_make = None
    camera_model = None
    datetime_original = None
    has_gps = False
    has_exif = False
    real_camera_make = False

    try:
        raw_exif = img._getexif()
        if raw_exif:
            has_exif = True
            exif_data = {
                ExifTags.TAGS.get(tag_id, str(tag_id)): val
                for tag_id, val in raw_exif.items()
            }
            camera_make = exif_data.get("Make")
            camera_model = exif_data.get("Model")
            datetime_original = (
                str(exif_data.get("DateTimeOriginal"))
                if exif_data.get("DateTimeOriginal")
                else None
            )
            has_gps = "GPSInfo" in exif_data

            if camera_make:
                make_lower = _lower_str(camera_make)
                real_camera_make = any(m in make_lower for m in _REAL_CAMERA_MAKES)
    except Exception:
        pass

    # ─────────────────────────────────────────────────────────────────────────
    # Step 3 — Software / Creator tag detection (most reliable metadata signal)
    # ─────────────────────────────────────────────────────────────────────────
    ai_software_detected = False
    ai_software_name = None

    # Fields to check for AI generator names
    software_fields_to_check = {
        "Software": exif_data.get("Software"),
        "Artist": exif_data.get("Artist"),
        "Copyright": exif_data.get("Copyright"),
        "ImageDescription": exif_data.get("ImageDescription"),
        "UserComment": exif_data.get("UserComment"),
        "MakerNote": None,  # checked separately
    }

    # Also check Pillow info dict for software-like keys
    for key in ("software", "creator", "author", "comment", "description"):
        if key in img_info:
            software_fields_to_check[f"PIL:{key}"] = img_info[key]

    for field_name, field_val in software_fields_to_check.items():
        if field_val is None:
            continue
        field_str = _lower_str(field_val)

        # Exact match against known AI tools
        for ai_name in _AI_SOFTWARE_EXACT:
            if ai_name in field_str:
                ai_software_detected = True
                ai_software_name = ai_name
                notes.append(
                    f"{_ts()} Software tag detection: '{ai_name}' found in {field_name} field"
                )
                signals.append(("ai_software_tag", 0.95, "ai", f"{field_name}={field_val!r:.80}"))
                break

        if ai_software_detected:
            break

        # Partial keyword match
        found, token = _contains_ai_token(field_str, _AI_SOFTWARE_PARTIAL)
        if found:
            ai_software_detected = True
            ai_software_name = token
            notes.append(
                f"{_ts()} Software tag detection: AI keyword '{token}' found in {field_name}"
            )
            signals.append(("ai_software_partial", 0.85, "ai", f"{field_name}={field_val!r:.80}"))
            break

    if not ai_software_detected:
        notes.append(f"{_ts()} Software tag detection: no known AI generator found in EXIF fields")

    # ─────────────────────────────────────────────────────────────────────────
    # Step 4 — PNG text chunk analysis (Stable Diffusion / ComfyUI fingerprint)
    # ─────────────────────────────────────────────────────────────────────────
    sd_png_params_found = False
    sd_png_key = None
    sd_png_snippet = None

    if fmt == "PNG":
        png_chunks = _read_png_text_chunks(image_path)

        # Also collect from Pillow's img.text (in case it picked up extras)
        pil_text = getattr(img, "text", {}) or {}
        for k, v in pil_text.items():
            if k not in png_chunks:
                png_chunks[k] = v

        for key, val in png_chunks.items():
            key_lower = key.lower().strip()
            val_lower = _lower_str(val)

            # Known SD/ComfyUI chunk keys
            if key_lower in _SD_PNG_KEYS:
                # Check the value contains actual AI content tokens
                found, token = _contains_ai_token(val_lower, _AI_CONTENT_TOKENS)
                if found or key_lower in ("parameters", "workflow", "invokeai_metadata", "invokeai_graph", "naidata"):
                    sd_png_params_found = True
                    sd_png_key = key
                    sd_png_snippet = val[:120].replace("\n", " ")
                    notes.append(
                        f"{_ts()} PNG chunk detection: key='{key}' contains AI generation params "
                        f"(token='{token}', snippet: {sd_png_snippet!r:.80})"
                    )
                    signals.append(("sd_png_chunk", 0.95, "ai", f"key={key}"))
                    break

            # Any chunk value that heavily matches SD tokens (even non-standard key)
            if not sd_png_params_found:
                count = sum(1 for t in _AI_CONTENT_TOKENS if t in val_lower)
                if count >= 3:
                    sd_png_params_found = True
                    sd_png_key = key
                    sd_png_snippet = val[:120].replace("\n", " ")
                    notes.append(
                        f"{_ts()} PNG chunk detection: key='{key}' has {count} AI tokens "
                        f"(snippet: {sd_png_snippet!r:.80})"
                    )
                    signals.append(("sd_png_chunk_multi_token", 0.90, "ai", f"key={key}, count={count}"))
                    break

        if not sd_png_params_found:
            notes.append(f"{_ts()} PNG chunk detection: no SD/ComfyUI parameter chunks found")
    else:
        notes.append(f"{_ts()} PNG chunk detection: skipped (format={fmt})")

    # ─────────────────────────────────────────────────────────────────────────
    # Step 5 — XMP / IPTC AI claims (Adobe Firefly, DALL-E, C2PA-embedded)
    # ─────────────────────────────────────────────────────────────────────────
    xmp_ai_claim_found = False
    xmp_ai_token_found = None
    xmp_raw = _extract_xmp(image_path, img_info)

    if xmp_raw:
        for token in _XMP_AI_TOKENS:
            if token.lower() in xmp_raw.lower():
                xmp_ai_claim_found = True
                xmp_ai_token_found = token
                notes.append(f"{_ts()} XMP detection: AI claim token '{token}' found in XMP metadata")
                signals.append(("xmp_ai_claim", 0.85, "ai", f"token={token}"))
                break

        # Also scan XMP for known AI generator names
        if not xmp_ai_claim_found:
            found, token = _contains_ai_token(xmp_raw, _AI_CONTENT_TOKENS + list(_AI_SOFTWARE_PARTIAL))
            if found:
                xmp_ai_claim_found = True
                xmp_ai_token_found = token
                notes.append(f"{_ts()} XMP detection: AI keyword '{token}' found in XMP data")
                signals.append(("xmp_ai_keyword", 0.80, "ai", f"token={token}"))

        if not xmp_ai_claim_found:
            notes.append(f"{_ts()} XMP detection: XMP found but no AI claims detected")
    else:
        notes.append(f"{_ts()} XMP detection: no XMP metadata found")

    # ─────────────────────────────────────────────────────────────────────────
    # Step 6 — C2PA byte-level scan
    # ─────────────────────────────────────────────────────────────────────────
    has_c2pa, c2pa_source = _scan_c2pa(image_path)
    c2pa_verdict = "unknown"

    if has_c2pa:
        c2pa_verdict = "AI"
        notes.append(f"{_ts()} C2PA scan: manifest/marker found ({c2pa_source}), verdict AI")
        signals.append(("c2pa_manifest", 0.85, "ai", c2pa_source))
    else:
        notes.append(f"{_ts()} C2PA scan: no C2PA/JUMBF markers detected")

    # ─────────────────────────────────────────────────────────────────────────
    # Step 7 — Camera EXIF richness scoring
    # ─────────────────────────────────────────────────────────────────────────
    # Core camera-only fields that are present in real photos but absent in AI images
    camera_fields = [
        "Make", "Model", "ExposureTime", "FNumber", "ISOSpeedRatings",
        "FocalLength", "Flash", "MeteringMode", "ExposureProgram",
        "DateTimeOriginal", "GPSInfo", "LensModel", "ShutterSpeedValue",
        "ApertureValue", "BrightnessValue", "LightSource",
    ]
    fields_found = sum(1 for f in camera_fields if f in exif_data)
    exif_score = round(fields_found / len(camera_fields), 2)

    notes.append(
        f"{_ts()} EXIF richness: {fields_found}/{len(camera_fields)} camera fields (score={exif_score})"
    )

    # High EXIF richness is a real-camera signal
    if exif_score >= 0.60 and real_camera_make:
        signals.append(("high_exif_richness_real_make", -0.35, "real",
                         f"score={exif_score}, make={camera_make}"))
        notes.append(f"{_ts()} EXIF richness: high score + verified real camera make → real signal")
    elif exif_score >= 0.40:
        signals.append(("moderate_exif_richness", -0.15, "real", f"score={exif_score}"))
        notes.append(f"{_ts()} EXIF richness: moderate camera EXIF → weak real signal")
    elif not has_exif:
        signals.append(("no_exif", 0.15, "ai", "no EXIF at all"))
        notes.append(f"{_ts()} EXIF richness: no EXIF data found → weak AI signal")
    else:
        notes.append(f"{_ts()} EXIF richness: sparse EXIF, inconclusive")

    # GPS in a real camera is common
    if has_gps and real_camera_make:
        signals.append(("gps_with_real_make", -0.10, "real", "GPS present + real camera make"))

    # ─────────────────────────────────────────────────────────────────────────
    # Step 8 — Compute Stage 1 AI score from signals
    # ─────────────────────────────────────────────────────────────────────────
    # Start from 0.5 (neutral), apply each signal's delta
    base = 0.50
    total_delta = 0.0

    for sig_name, weight, direction, detail in signals:
        if direction == "ai":
            total_delta += weight
        else:  # real
            total_delta -= abs(weight)

    stage1_ai_score = round(min(1.0, max(0.0, base + total_delta * 0.5)), 4)

    # If a definitive AI signal is present, pin to at least 0.85
    definitive_ai = (
        ai_software_detected
        or sd_png_params_found
    )
    if definitive_ai:
        stage1_ai_score = max(stage1_ai_score, 0.85)

    # If a definitive real signal and no AI signals, pin to at most 0.30
    strong_real = (
        real_camera_make
        and exif_score >= 0.60
        and not ai_software_detected
        and not sd_png_params_found
        and not xmp_ai_claim_found
        and not has_c2pa
    )
    if strong_real:
        stage1_ai_score = min(stage1_ai_score, 0.30)

    notes.append(
        f"{_ts()} Stage 1 score: {stage1_ai_score} "
        f"(signals: {[s[0] for s in signals]})"
    )

    # ─────────────────────────────────────────────────────────────────────────
    # Step 9 — Early exit decision
    # ─────────────────────────────────────────────────────────────────────────
    # Fire early exit (skip Stage 2 Hive API) only when we have high confidence
    early_exit = False
    early_exit_verdict = None

    if ai_software_detected or sd_png_params_found:
        # Software tag or SD params chunk = definitive proof; skip API call
        early_exit = True
        early_exit_verdict = "LIKELY_AI"
        notes.append(
            f"{_ts()} Early exit TRIGGERED: definitive AI metadata found "
            f"(software={ai_software_name}, sd_png={sd_png_params_found}) → Stage 2 skipped"
        )
    elif strong_real:
        # Clear real camera → skip API call (save cost), declare LIKELY_REAL
        early_exit = True
        early_exit_verdict = "LIKELY_REAL"
        notes.append(
            f"{_ts()} Early exit TRIGGERED: strong real camera metadata "
            f"(make={camera_make}, EXIF={exif_score}) → Stage 2 skipped as LIKELY_REAL"
        )
    else:
        notes.append(f"{_ts()} Early exit: not triggered — proceeding to Stage 2")

    # ─────────────────────────────────────────────────────────────────────────
    # Assemble result
    # ─────────────────────────────────────────────────────────────────────────
    return {
        "stage": 1,
        "image_path": image_path,
        # Definitive signals
        "ai_software_detected": ai_software_detected,
        "ai_software_name": ai_software_name,
        "sd_png_params_found": sd_png_params_found,
        "xmp_ai_claim_found": xmp_ai_claim_found,
        "has_c2pa": has_c2pa,
        "c2pa_verdict": c2pa_verdict,
        # EXIF richness
        "has_exif": has_exif,
        "exif_score": exif_score,
        "camera_make": camera_make,
        "camera_model": camera_model,
        "datetime_original": datetime_original,
        "has_gps": has_gps,
        "real_camera_make": real_camera_make,
        # File props
        "file_size_kb": file_size_kb,
        "format": fmt,
        "width": width,
        "height": height,
        # Stage 1 verdict
        "stage1_ai_score": stage1_ai_score,
        "stage1_signals": [
            {"signal": s[0], "weight": s[1], "direction": s[2], "detail": s[3]}
            for s in signals
        ],
        "early_exit": early_exit,
        "early_exit_verdict": early_exit_verdict,
        "pipeline_notes": notes,
        "error": None,
    }


if __name__ == "__main__":
    import sys
    result = run(sys.argv[1])
    print(json.dumps(result, indent=2, default=str))
